### PR TITLE
Fix album cover art not displaying

### PR DESCRIPTION
**Pull request by yorunoken**
in line 125:
`cover_img = title.replace(" ", "").lower()`
`cover_img` is passed to the `large_image` argument, but that argument needs to be a link.
in the PR, I assigned `cover_img` to `cover_url`, which is the correct solution to the cover art not being displayed in Discord.

I also removed `small_image` completely since it looks better like that. Let me know if you want me to revert that.

### CODE REVIEW

**Comment by M1ndo** [comment]
Thanks for the PR @yorunoken we'll check it out and let you know.

**Review by M1ndo — CHANGES_REQUESTED** [review]
As i checked it turns out that Discord no longer requires to upload assets in order to view images, which you had to wait 10-15min before those images gets displayed when listening to a song.
for `check_url` it was used to check if the image was already uploaded in discord assets so we don't upload the same image twice.

`small_image` options is required to display like an artist image or something custom.

image

I can merge your request, however can you uncomment the `small_image` params its necessary.

Thanks!

**Comment by yorunoken** [comment]
> `small_image` options is required to display like an artist image or something custom.

this is untrue, as mine was working without passing in `small_image`. I'll uncomment it in a bit

**Comment by yorunoken** [comment]
should be ready to merge now

**Comment by M1ndo** [comment]
> should be ready to merge now

Thanks, its merged!

**Pull request merged**
